django_projects/mysite/ads/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='ads'
urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create',
        views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ad/<int:pk>/update',
        views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ad/<int:pk>/delete',
        views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    path('ad/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('ads')), name='ad_comment_delete'),
    path('ad/<int:pk>/favorite',
        views.AddFavoriteView.as_view(), name='ad_favorite'),
    path('ad/<int:pk>/unfavorite',
        views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),

]

django_projects/mysite/cities/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

# https://docs.djangoproject.com/en/3.0/topics/http/urls/
app_name = 'cities'
urlpatterns = [
    path('', views.CityList.as_view(), name='all'),
    path('main/create/', views.CityCreate.as_view(), name='city_create'),
    path('main/<int:pk>/update/', views.CityUpdate.as_view(), name='city_update'),
    path('main/<int:pk>/delete/', views.CityDelete.as_view(), name='city_delete'),
    path('lookup/', views.StateView.as_view(), name='state_list'),
    path('lookup/create/', views.StateCreate.as_view(), name='state_create'),
    path('lookup/<int:pk>/update/', views.StateUpdate.as_view(), name='state_update'),
    path('lookup/<int:pk>/delete/', views.StateDelete.as_view(), name='state_delete'),
]

django_projects/mysite/mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve

urlpatterns = [
    path('', include('home.urls')),  # Change to ads.urls
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep

    path('ads/', include('ads.urls')),
    path('solo/', include('solo.urls')),

]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

django_projects/mysite/cities/models.py
from django.db import models
from django.core.validators import MinLengthValidator

class State(models.Model):
    name = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "State must be greater than 1 character")]
    )

    def __str__(self):
        return self.name

class City(models.Model):
    nickname = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Nickname must be greater than 1 character")]
    )
    population = models.PositiveIntegerField()
    slogan = models.CharField(max_length=300)
    state = models.ForeignKey('State', on_delete=models.CASCADE, null=False)

    def __str__(self):
        return self.nickname

django_projects/mysite/cities/forms.py
from django.forms import ModelForm
from cities.models import State


# Create the form class.
class StateForm(ModelForm):
    class Meta:
        model = State
        fields = '__all__'

django_projects/mysite/cities/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from cities.models import City, State
from cities.forms import StateForm

# Create your views here.


class CityList(LoginRequiredMixin, View):
    def get(self, request):
        sc = State.objects.all().count()
        cl = City.objects.all()

        ctx = {'state_count': sc, 'city_list': cl}
        return render(request, 'cities/city_list.html', ctx)


class StateView(LoginRequiredMixin, View):
    def get(self, request):
        sl = State.objects.all()
        ctx = {'state_list': sl}
        return render(request, 'cities/state_list.html', ctx)


# We use reverse_lazy() because we are in "constructor attribute" code
# that is run before urls.py is completely loaded
class StateCreate(LoginRequiredMixin, View):
    template = 'cities/state_form.html'
    success_url = reverse_lazy('cities:all')

    def get(self, request):
        form = StateForm()
        ctx = {'form': form}
        return render(request, self.template, ctx)

    def post(self, request):
        form = StateForm(request.POST)
        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template, ctx)

        make = form.save()
        return redirect(self.success_url)


# MakeUpdate has code to implement the get/post/validate/store flow
# AutoUpdate (below) is doing the same thing with no code
# and no form by extending UpdateView
class StateUpdate(LoginRequiredMixin, View):
    model = State
    success_url = reverse_lazy('cities:all')
    template = 'cities/state_form.html'

    def get(self, request, pk):
        make = get_object_or_404(self.model, pk=pk)
        form = StateForm(instance=make)
        ctx = {'form': form}
        return render(request, self.template, ctx)

    def post(self, request, pk):
        make = get_object_or_404(self.model, pk=pk)
        form = StateForm(request.POST, instance=make)
        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template, ctx)

        form.save()
        return redirect(self.success_url)


class StateDelete(LoginRequiredMixin, View):
    model = State
    success_url = reverse_lazy('cities:all')
    template = 'cities/state_confirm_delete.html'

    def get(self, request, pk):
        make = get_object_or_404(self.model, pk=pk)
        form = StateForm(instance=make)
        ctx = {'make': make}
        return render(request, self.template, ctx)

    def post(self, request, pk):
        make = get_object_or_404(self.model, pk=pk)
        make.delete()
        return redirect(self.success_url)


# Take the easy way out on the main table
# These views do not need a form because CreateView, etc.
# Build a form object dynamically based on the fields
# value in the constructor attributes
class CityCreate(LoginRequiredMixin, CreateView):
    model = City
    fields = '__all__'
    success_url = reverse_lazy('cities:all')


class CityUpdate(LoginRequiredMixin, UpdateView):
    model = City
    fields = '__all__'
    success_url = reverse_lazy('cities:all')


class CityDelete(LoginRequiredMixin, DeleteView):
    model = City
    fields = '__all__'
    success_url = reverse_lazy('cities:all')


# Create your views here.

django_projects/mysite/cities/templates/cities/city_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete City</h1>

<p>Are you sure you want to delete the city: {{ city }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

django_projects/mysite/cities/templates/cities/city_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'cities:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

django_projects/mysite/cities/templates/cities/city_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>City List</h1>
  {% if city_list %}
  <ul>
    {% for city in city_list %}
      <li>
          {{ city.nickname }} ({{ city.make }})
          (<a href="{% url 'cities:city_update' city.id %}">Update</a> |
          <a href="{% url 'cities:city_delete' city.id %}">Delete</a>) <br/>
          {{ city.comments }} ({{ city.mileage }} miles)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no cities in the library.</p>
  {% endif %}
  <p>
    {% if state_count > 0 %}
      <a href="{% url 'cities:city_create' %}">Add a city</a>
    {% else %}
      Please add a state before you add an city.
    {% endif %}
  </p>
  <p>
  <a href="{% url 'cities:state_list' %}">View states</a> ({{ state_count }}) |
    <a href="{% url 'cities:state_create' %}">Add a state</a>
  </p>
{% endblock %}

django_projects/mysite/cities/templates/cities/state_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete State</h1>

<p>Are you sure you want to delete the state: {{ state }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" onclick="window.location='{% url 'cities:all' %}' ; return false;" value="Cancel">
</form>

{% endblock %}

django_projects/mysite/cities/templates/cities/state_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'cities:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

django_projects/mysite/cities/templates/cities/state_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>State List</h1>
  {% if state_list %}
  <ul>
    {% for state in state_list %}
      <li>
          {{ state.name }}
         (<a href="{% url 'cities:state_update' state.id %}">Update</a> |
          <a href="{% url 'cities:state_delete' state.id %}">Delete</a>)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no states in the library.</p>
  {% endif %}
  <p><a href="{% url 'cities:state_create' %}">Add a state</a></p>
  <p>
    <a href="{% url 'cities:all' %}">Back to cities</a>
  </p>
{% endblock %}